### ISSUE TITLE
PDF generation not working?

### ISSUE THREAD

**Issue by Roeligan** [thomascenni/alpine-invoiceplane#1]
Love this container, it's virtually the only one that works out of the box, but for some reason PDF generation is not working?
Any idea?

**Comment by thomascenni** [comment]
Hi @Roeligan 
I'm using it and also PDF generation works out of the box. InvoicePlane uses the mPDF library.
What are the errors you are getting?

**Comment by Roeligan** [comment]
Hi @thomascenni,

Hmm.... well, I don't get an error at all; it is just not really triggering the pdf creation (not for invoice nor for offerings.  Eventually it just times out, but it seems nothing is happening at all with those clicks.  And that's only for PDF, all the others seem to work just fine.
First thought it was a routing thing or so; I do have an nginx proxy in front of it, but all the other links are working just fine and it does seem to get through according to the invoiceplane error log (which is just the timeout imho; I renamed the domain): 

2021/06/04 11:10:54 [error] 304#304: *8069 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.17.0.1, server: http, request: "GET /invoices/generate_pdf/127 HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock", host: "sub.mydomain.com", referrer: "https://sub.mydomain.com/"
2021/06/04 11:10:54 [error] 304#304: *8069 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: 172.17.0.1, server: http, request: "GET /invoices/generate_pdf/127 HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock", host: "sub.mydomain.com", referrer: "https://sub.mydomain.com/"

**Comment by thomascenni** [comment]
Hello,
Just googling, I found this discussion topic on InvoicePlane community:

https://community.invoiceplane.com/t/topic/5617

I can't really help more than that, you should look for info on InvoicePlane side.
This repository is only about a custom Docker container implementation.

**Comment by Roeligan** [comment]
Hi, found the issue :)
the container required an additional host entry to resolve the domain for PDF creation.

**Comment by MrCee** [comment]
@Roeligan Same issue, I'd love to know what you did exactly? Much appreciated.

**Comment by Roeligan** [comment]
@MrCee I added an additional host entry to the docker command; pointing the domain to the ip where my nginx reverse proxy container is running (happens to be the same ip but different port as invoiceplane container is running).
If you use docker compose it's something like:
extra_hosts:
 - "invoice.mydomain.com:10.10.10.10"
